### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by doko-desuka** [Prometheusx-git/plugin.video.unofficial9anime#1]
Hello!
>This add-on requires dependencies only found in the repository.

Are these dependencies the "script.module.dat1guy.shared" and "script.module.animemetahandler", the other repositories you have?

Sorry for the noob question. How can I manually install all these in my Kodi Krypton 17.4?

**Comment by doko-desuka** [comment]
So I see now, after reading this:
http://kodi.wiki/view/Add-on_structure#addon.xml

The addon.xml file from this video plugin says that it needs the script modules that you also share in your repos:
https://github.com/Prometheusx-git/plugin.video.unofficial9anime/blob/master/addon.xml#L5-L8

There doesn't seem to be a "kodi add-on repository" for your unnoficial9anime fork. Could you make one?
Otherwise people can download the master ZIP of each repository and install them manually I think.

**Comment by Prometheusx-git** [comment]
This readme text is from the original addon.

The files script.module.dat1guy.shared and script.module.animemetahandler are needed.
The other 2 dependencies are fairly common i think, i will add them later. 
There is no kodi repo yet, maybe later.
For now the installation has to be manually, so download the zips, delete "-master" from the filename.
Then in Kodi there is in system the dialog "install from zip".

**Comment by doko-desuka** [comment]
Thank you. I will give that a try.

**Comment by doko-desuka** [comment]
I installed all addons (in this order: "dat1guy.shared", then "animemetahandler" and finally "unofficial9anime").

I can enter the add-on with Kodi and go to the settings.

When I submit a text to search or when I try to see genre categories, it gives an unknown error ("check the log"), but I don't know what log to look into. It's not in the Kodi system log.

**Comment by Prometheusx-git** [comment]
In Kodi under Settings -> System -> Logging are Buttons to activate Logging.
Could you upload the kodi.log after getting the error?

**Comment by doko-desuka** [comment]
Understood. kodi.log, I'll take a look into it.

**Comment by doko-desuka** [comment]
I started Kodi, then started the UP9Anime addon, went to 'Browse -> Newest Added' to produce the error, then took the kodi.log:

[https://nofile.io/f/fVWVSdBZGcf/kodi.log](https://nofile.io/f/fVWVSdBZGcf/kodi.log)

**Comment by Prometheusx-git** [comment]
Thanks for the log.
I have found a problem in the animemetahandler.
Please try the new version from 

https://github.com/Prometheusx-git/repo.zips/blob/master/script.module.animemetahandler-1.0.5.zip

If it still doesn't work, upload a new kodi.log.

**Comment by doko-desuka** [comment]
Thank you for the fix.
I think I'm gonna close the issue since it was solved (getting to know how to install the add-on).

 If I find other errors I'll create a new issue and post the log like you said.
