### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by Bronsgrinder** [Prometheusx-git/plugin.video.unofficial9anime#2]
First of all I like the addon keep up the good work.

So far I have found 3 issues in the addon:

1. When you want to watch an OVA or special it don't work. You get a menu up but after you select video quality its show just an empty folder instead of the video.

2. When you search and there is more than 30 matches found than you can only use the first 30 without a option to go to the next page or load more. Most time not a big issue but there are exceptions. The same also happend when you ga to Browse and than a sub menu like Movies or all other options there listed. 

3. In Browse menu the submenu Trending gives an error.

Hopefully it is clear enough what I mean. My English is not so good

**Comment by Prometheusx-git** [comment]
Hi,

the 3 issues should be fixed with the new version 1.0.9

**Comment by Bronsgrinder** [comment]
Yes its is fixed. Ty for fast update.
